name: octopus-mpf-db
services:
  mariadb:
    image: mariadb:11.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mpf_db
      MYSQL_USER: mpf_user
      MYSQL_PASSWORD: mpf_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: mpf_user
      PMA_PASSWORD: mpf_password
    depends_on:
      - mariadb

volumes:
  db_data: 