import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Providers from "./Providers";
import Breadcrumbs from "./Breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="navbar bg-base-100 shadow mb-8">
            <div className="flex-1">
              <Link href="/" className="btn btn-ghost normal-case text-xl">MPF & RF FFESSM</Link>
            </div>
            <div className="flex-none gap-2">
              <Link href="/records" className="btn btn-ghost">Records</Link>
              <Link href="/competiteurs" className="btn btn-ghost">Compétiteurs</Link>
              <Link href="/epreuves" className="btn btn-ghost">Épreuves</Link>
              <Link href="/login" className="btn btn-primary">Connexion</Link>
            </div>
          </div>
          <main className="container mx-auto px-4">
          <Breadcrumbs />
            {children}
            </main>
        </Providers>
      </body>
    </html>
  );
}
